name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy To Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM modules and build Gatsby site
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - run: npm install
      - run: cp src/config/ProductionConfig.json src/config/Config.json
      - run: npm run build
      - name: Empty public/ artifact folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /root/.bashrc
            cd "/root/projects/chrisfrew.in/"
            rm -R public/**
      - name: Copy public/ to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "public"
          target: "/root/projects/chrisfrew.in"
          overwrite: true
      - name: Copy node_modules/ to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "node_modules"
          target: "/root/projects/chrisfrew.in"
          overwrite: true
      - name: Pull newest repository source and restart (or start) node forever on the server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /root/.bashrc
            cd "/root/projects/chrisfrew.in/"
            git pull
            forever restart index.js || forever start index.js && echo 'Forever successfully running!'
      - name: Send slack notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Build complete! Latest commit message:"
          SLACK_ICON: "https://avatars.slack-edge.com/2021-02-01/1723555500368_e97655869409251d202e_96.jpg"
