name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy To Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM modules and build Gatsby site
        uses: actions/setup-node@v1
        with:
          node-version: '12.17.0'
      - run: npm install
      - run: npm run build
      - name: Copy public (build) directory to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "public"
          target: "/root/projects/chrisfrew.in"
          overwrite: true
      - name: Restart (or start when restart fails) node forever on the server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /root/.bashrc
            cd "/root/projects/chrisfrew.in/"
            forever restart index.js || forever start index.js && echo 'Forever successfully running!'
      - name: Send slack notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Build complete! Latest commit message:"